name: flutter_app2
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/rey.jpg
    - images/tolu1.jpg
    - images/tolu2.jpg
    - images/ich.jpg
    - images/pokemon.jpg
    - images/bulb.jpeg
    - images/plane.jpeg

  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  - family: Grenze Gotisch
    fonts:
    - asset: fonts/GrenzeGotisch-Light.ttf

  - family: ComicNeue-Light
    fonts:
    - asset: fonts/ComicNeue-Light.ttf

  - family: ComicNeue-Bold
    fonts:
    - asset: fonts/ComicNeue-Bold.ttf